chore: upgrade helm to v3.14.0

diff --git a/core b/core
--- a/core
+++ b/core
@@ -1,7 +1,13 @@
 #!/bin/bash
 
 install() {
+  # prepare vars
+  local name="$PACKAGE_CORE_NAME"
+
+  log::info "[$(timestamp)][package][$name] preparing ..."
+
   # get system os/arch
+  local os="$PACKAGE_OS"
   local arch="$PACKAGE_OS_ARCH"
   local kernel="$PACKAGE_OS_KERNEL"
   local platform="$PACKAGE_OS_PLATFORM"
@@ -9,34 +15,90 @@ install() {
   local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
   local tmp_dir="$PACKAGE_TMP_DIR"
 
-  # prepare vars
-  local name="helm"
+  # #
+  # case $platform in
+  # darwin)
+  #   platform="osx"
+  #   ;;
+  # linux) ;;
+
+  # *)
+  #   log::error "[$(timestamp)] unsupport platform: $platform"
+  #   return 1
+  #   ;;
+  # esac
+
+  # case $arch in
+  # arm64) ;;
+
+  # amd64)
+  #   arch="x86_64"
+  #   ;;
+  # *)
+  #   log::error "[$(timestamp)] unsupport arch: $arch"
+  #   return 1
+  #   ;;
+  # esac
+  # #
+
+  # # get latest version
+  # log::info "[$(timestamp)][package][$name] checking latest version ..."
+  # local latest_version=$(git::get_remote_latest_tag $PACKAGE_CORE_GIT_REPOSITORY)
+  # if [ "$?" != "0" ]; then
+  #   log::error "[$(timestamp)][package][$name] failed to get latest version ."
+  #   return 1
+  # fi
+  # PACKAGE_CORE_VERSION=$latest_version
+  # log::success "[$(timestamp)][package][$name] latest version: $PACKAGE_CORE_VERSION"
+
   # files
   local tmp_file="$name.tar.gz"
-  local bin_file="./${platform}-${arch}/$name"
-
-  # prepare context
-  cd $tmp_dir
-
+  local source_bin_file="./${platform}-${arch}/$name"
   # reference: https://github.com/helm/helm/releases
   # example:
   #   https://get.helm.sh/helm-v3.10.2-darwin-arm64.tar.gz
   #   https://get.helm.sh/helm-v3.10.2-darwin-amd64.tar.gz
   # generate url
-  local url="https://get.helm.sh/${name}-${PACKAGE_CORE_VERSION}-${platform}-${arch}.tar.gz"
-  log::debug "[package][$name][$kernel][$arch] url: $url"
+  local url="${PACKAGE_CORE_RELEASE_DOWNLOAD}/${name}-${PACKAGE_CORE_VERSION}-${platform}-${arch}.tar.gz"
+  log::debug "[$(timestamp)][package][$name][$kernel][$arch] url: $url, file: ${tmp_file}, tmp_dir: $tmp_dir"
+
+  log::info "[$(timestamp)][package][$name] os: $os"
+  log::info "[$(timestamp)][package][$name] arch: $arch"
+  log::info "[$(timestamp)][package][$name] kernel: $kernel"
+  log::info "[$(timestamp)][package][$name] platform: $platform"
+  log::info "[$(timestamp)][package][$name] usr_bin_dir: $usr_bin_dir"
+  log::info "[$(timestamp)][package][$name] source_bin_file: $source_bin_file"
+  log::info "[$(timestamp)][package][$name] url: $url"
+  log::info "[$(timestamp)][package][$name] tmp_dir: $tmp_dir"
+  log::info "[$(timestamp)][package][$name] tmp_file: $tmp_file"
+  if [ -n "$PLUGIN_PACKAGE_INSTALL_MODE" ]; then
+    log::info "[$(timestamp)][package][$name] mode: $PLUGIN_PACKAGE_INSTALL_MODE"
+  fi
+
+  # prepare context
+  cd $tmp_dir
 
   # download
+  log::info "[$(timestamp)][package][$name] downloading ..."
   os::download $tmp_file $url
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)][package][$name] failed to download from $url ."
+    return 1
+  fi
 
   # extract
-  tar -zxvf $tmp_file >>/dev/null 2>&1
+  log::info "[$(timestamp)][package][$name] extracting ..."
+  os::extract $tmp_file
 
   # install
-  sudo mv $bin_file $usr_bin_dir
+  log::info "[$(timestamp)][package][$name] installing ..."
+  os::install $source_bin_file $usr_bin_dir $name
 
-  # clean
-  rm -rf $tmp_dir
+  if [ "$PLUGIN_PACKAGE_INSTALL_MODE" != "test" ]; then
+    # clean
+    log::info "[$(timestamp)][package][$name] cleaning ..."
+    rm -rf $tmp_dir
+  fi
 }
 
 export -f install
